[tools]
ast-grep = "0.42.2"
cargo-binstall = "1.19.1"
"cargo:bob-nvim" = "4.1.7"
"cargo:eza" = "0.23.4"
"cargo:ripgrep" = "15.1.0"
"cargo:zellij" = "0.44.3"
"cargo:zoxide" = "0.9.9"
"cargo:yazi-fm" = "latest"
"cargo:bat" = "latest"
rust = "1.95.0"
dotnet = "latest"
fd = "10.4.2"
fzf = "0.72.0"
ghcup = "0.1.50.2"
go = "1.26.3"
java = "26.0.1"
jq = "1.8.1"
maven = "3.9.15"
pipx = "1.12.0"
"pipx:virtualfish" = "2.5.9"
poetry = "2.4.1"
shfmt = "3.13.1"
starship = "1.25.1"
usage = "3.3.0"
zig = "0.16.0"
zoxide = "0.9.9"
uv = "0.11.14"
dart = { version = "3.11.6", url = "https://storage.googleapis.com/dart-archive/channels/stable/release/{{ version }}/sdk/dartsdk-linux-x64-release.zip", version_expr = 'fromJSON(body).prefixes | filter({ # matches "^channels/stable/release/(\\d+\\.\\d+\\.\\d+)/$" }) | map({split(#, "/")[3]}) | sortVersions()', version_list_url = "https://storage.googleapis.com/storage/v1/b/dart-archive/o?prefix=channels/stable/release/&delimiter=/" }
node = "26.1.0"
"go:github.com/jesseduffield/lazygit" = "0.61.1"
pnpm = "latest"
bun = "latest"
opencode = "latest"
"dotnet:uno.check" = "latest"
"dotnet:easydotnet" = "latest"
deno = "latest"
lua = "latest"
"cargo:jiq" = "latest"
"aqua:anthropics/claude-code" = "2.1.143"
tree-sitter = "latest"
"go:go.senan.xyz/cliphist" = "latest"
"github:bluesabre/menulibre" = "latest"
jqp = "latest"
watchexec = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[settings.npm]
package_manager = "bun"

[settings.aqua]
registry_url = "https://github.com/aquaproj/aqua-registry"

[settings.ruby]
compile = false
